name = "vless-workers-pages"
main = "Vless_workers_pages/worker.js"
compatibility_date = "2024-10-04"

# ====================================================================
# NAT64 套壳版混淆配置
# ====================================================================
# 特点：
# ✅ 自动使用 NAT64 转换生成 ProxyIP
# ✅ 自动支持访问 CF 类网站（Twitter/X、ChatGPT 等）
# ✅ 零配置，开箱即用
# ⚠️ 不支持自定义 proxyip（已内置自动处理，设置无效）
# ====================================================================

[vars]
# ====================================================================
# 必需配置：UUID（用于身份验证）
# ====================================================================
# 生成UUID方法：
#   Windows PowerShell: [guid]::NewGuid()
#   Linux/Mac: uuidgen
# ⚠️ 强烈建议修改为你自己的UUID！
# ====================================================================
uuid = "e594c2ac-961e-44ca-a989-879103c4e58b"

# ====================================================================
# 可选配置：自定义订阅节点的优选IP和端口
# ====================================================================
# 说明：
# - 以下配置仅影响订阅链接中的节点
# - 新手用户使用默认值即可，无需修改
# - ip1-ip7 对应 HTTP 端口（pt1-pt7，关闭TLS）
# - ip8-ip13 对应 HTTPS 端口（pt8-pt13，开启TLS）
# ====================================================================

# CDN IP配置
# cdnip = "www.visa.com.sg"

# HTTP 端口优选IP（关闭TLS）
# ip1 = "www.visa.com"
# ip2 = "cis.visa.com"
# ip3 = "africa.visa.com"
# ip4 = "www.visa.com.sg"
# ip5 = "www.visaeurope.at"
# ip6 = "www.visa.com.mt"
# ip7 = "qa.visamiddleeast.com"

# HTTPS 端口优选IP（开启TLS）
# ip8 = "usa.visa.com"
# ip9 = "myanmar.visa.com"
# ip10 = "www.visa.com.tw"
# ip11 = "www.visaeurope.ch"
# ip12 = "www.visa.com.br"
# ip13 = "www.visasoutheasteurope.com"

# HTTP 端口配置（80系端口，关闭TLS）
# pt1 = "80"
# pt2 = "8080"
# pt3 = "8880"
# pt4 = "2052"
# pt5 = "2082"
# pt6 = "2086"
# pt7 = "2095"

# HTTPS 端口配置（443系端口，开启TLS）
# pt8 = "443"
# pt9 = "8443"
# pt10 = "2053"
# pt11 = "2083"
# pt12 = "2087"
# pt13 = "2096"